version: "3"

#networks:
#  gitea:
#    external: false

volumes:
  gitea:
    driver: local

services:
  server:
    image: "datbeohbbg/gitea:latest"
    container_name: gitea
    restart: always
    #networks:
    #  - gitea
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=$POSTGRES_DB
      - GITEA__database__USER=$POSTGRES_USER
      - GITEA__database__PASSWD=$POSTGRES_PASSWORD
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    - "3000:3000"
    - "2221:22"
    depends_on:
      - postgres

  postgres:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    #networks:
    #  - gitea
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"