version: "3"

volumes:
  gitea:
    driver: local

services:
  server:
    image: "datbeohbbg/gitea:latest"
    mem_limit: 512m
    container_name: gitea
    restart: always
    environment:
      - GITEA__database__DB_TYPE=$GITEA_DB_TYPE 
      - GITEA__database__HOST=$GITEA_DB_HOST 
      - GITEA__database__NAME=$GITEA_DB_NAME 
      - GITEA__database__USER=$GITEA_DB_USER 
      - GITEA__database__PASSWD=$GITEA_DB_PASSWD 
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    - "80:3000"
    - "2222:22"
